FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

RUN npm install -g nodemon

COPY package*.json ./

RUN npm install

RUN npm install pg @types/pg file-type@16.5.4

COPY . .

RUN mkdir -p /app/uploads

EXPOSE 3000
EXPOSE 50052

CMD ["sh", "-c", "npm run build && node dist/main.js"]