syntax = "proto3";

package users;

service UsersService {
    rpc GetKiosksAvailability (KiosksAvailabilityRequest) returns (KiosksAvailabilityResponse);
    rpc GetUserProfile (GetUserProfileRequest) returns (UserProfile);
    rpc GetUserAddress (GetUserAddressRequest) returns (GetUserAddressResponse);
}

message KiosksAvailabilityRequest {
    repeated string kioskIds = 1;
}

message KiosksAvailabilityResponse {
    repeated KioskAvailability items = 1;
}

message KioskAvailability {
    string kioskId = 1;
    bool isAvailable = 2;
    string reason = 3;
}

message GetUserProfileRequest {
    string userId = 1;
}

message UserProfile {
    string userId = 1;
    string email = 2;
    string username = 3;
}

message GetUserAddressRequest {
    string userId = 1;
}

message GetUserAddressResponse {
    string userId = 1;
    double latitude = 2;
    double longitude = 3;
    string addressLine = 4;
}