// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v5.29.3
// source: users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface KiosksAvailabilityRequest {
  kioskIds: string[];
}

export interface KiosksAvailabilityResponse {
  items: KioskAvailability[];
}

export interface KioskAvailability {
  kioskId: string;
  isAvailable: boolean;
  reason: string;
}

export interface GetUserProfileRequest {
  userId: string;
}

export interface UserProfile {
  userId: string;
  email: string;
  username: string;
}

export const USERS_PACKAGE_NAME = "users";

export interface UsersServiceClient {
  getKiosksAvailability(request: KiosksAvailabilityRequest): Observable<KiosksAvailabilityResponse>;

  getUserProfile(request: GetUserProfileRequest): Observable<UserProfile>;
}

export interface UsersServiceController {
  getKiosksAvailability(
    request: KiosksAvailabilityRequest,
  ): Promise<KiosksAvailabilityResponse> | Observable<KiosksAvailabilityResponse> | KiosksAvailabilityResponse;

  getUserProfile(request: GetUserProfileRequest): Promise<UserProfile> | Observable<UserProfile> | UserProfile;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getKiosksAvailability", "getUserProfile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
