export enum ContractStatus {
  DRAFT = 'DRAFT',
  NEGOTIATION = 'NEGOTIATION',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  BLOCKED = 'BLOCKED'
}